export const pilotos = [
  "Lando Norris",
  "Oscar Piastri",
  "Max Verstappen",
  "Yuki Tsunoda",
  "Charles Leclerc",
  "Lewis Hamilton",
  "George Russell",
  "Kimi Antonelli",
  "Pierre Gasly",
  "Jack Doohan",
  "Esteban Ocon",
  "Oliver Bearman",
  "Fernando Alonso",
  "Lance Stroll",
  "Alexander Albon",
  "Carlos Sainz",
  "Nico Hülkenberg",
  "Gabriel Bortoleto",
  "Liam Lawson",
  "Isack Hadjar",
  "Valteri Bottas",
  "Sérgio Perez",
  "Ayrton Senna",
  "Michael Schumacher",
];
